apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "ecommerce"
        - name: POSTGRES_PASSWORD
          value: "Pg1234"
        - name: POSTGRES_DB
          value: "ecommerce"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: postgre

---
apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000 
    nodePort: 30001    
  selector:
    app: fakeshop

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
      - name: fakeshop
        image: eliasassuncao100/fake-shop:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgre"
        - name: DB_USER 
          value: "ecommerce"
        - name: DB_PASSWORD
          value: "Pg1234"
        - name: DB_NAME
          value: "ecommerce"
        - name: DB_PORT
          value: "5432"
        - name: FLASK_APP
          value: "index.py"
